# Generated by Django 5.2 on 2025-04-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentesreview', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcionesdepatio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcionesrevisiom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('tipodeequipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serialnumber', models.CharField(max_length=100)),
                ('ipaddress', models.GenericIPAddressField()),
                ('procesador', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=100)),
                ('imgantes', models.ImageField(upload_to='imagenesantes/')),
                ('imgdespues', models.ImageField(upload_to='imagenesdespues/')),
                ('tempcpu', models.CharField(max_length=100)),
                ('imgtemp', models.ImageField(upload_to='tempcpu/')),
                ('imgagent', models.ImageField(upload_to='tempcpu/')),
                ('agent', models.ManyToManyField(to='supdata.agentes')),
                ('patio', models.ManyToManyField(to='supdata.patios')),
            ],
        ),
    ]
