# Generated by Django 5.2 on 2025-04-15 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='opcionesrevisiom',
            new_name='opcionesrevision',
        ),
        migrations.AddField(
            model_name='data',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
