# Generated by Django 5.2 on 2025-04-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0004_data_firma_data_mtto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='planta',
        ),
    ]
