# Generated by Django 5.2 on 2025-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0005_remove_data_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='patio',
        ),
        migrations.AddField(
            model_name='data',
            name='planta',
            field=models.CharField(default='datos', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='patios',
        ),
    ]
