# Generated by Django 5.2 on 2025-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0006_remove_data_patio_data_planta_delete_patios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentes',
            name='agentesreview',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='opcionesrevision',
        ),
        migrations.AddField(
            model_name='agentes',
            name='borrartemporales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentes',
            name='encriptacionhdd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentes',
            name='epc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentes',
            name='sophos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentes',
            name='tenable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentes',
            name='updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='empresa',
            field=models.CharField(default='Cissa, Intelred etc...', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='nombretech',
            field=models.CharField(default='Escriba su nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='aplicacionpasta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limpexterna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limpiezadisipador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limpinterna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limppasta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limpram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limpteclado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='limpventilador',
            field=models.BooleanField(default=False),
        ),
    ]
