# Generated by Django 5.2 on 2025-04-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0007_remove_agentes_agentesreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='departamento',
            field=models.CharField(default='Escriba el departamento del usuario', max_length=100),
            preserve_default=False,
        ),
    ]
