# Generated by Django 5.2 on 2025-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0008_data_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='activofijo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
