# Generated by Django 5.2 on 2025-04-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0009_data_activofijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='data',
            name='mtto',
        ),
        migrations.AddField(
            model_name='data',
            name='agent',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='supdata.agentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='mtto',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='supdata.revision'),
            preserve_default=False,
        ),
    ]
