# Generated by Django 5.2 on 2025-04-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0010_remove_data_agent_remove_data_mtto_data_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supdata.agentes'),
        ),
        migrations.AlterField(
            model_name='data',
            name='mtto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supdata.revision'),
        ),
    ]
