# Generated by Django 5.2 on 2025-04-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0011_alter_data_agent_alter_data_mtto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='data',
            name='mtto',
        ),
        migrations.AddField(
            model_name='data',
            name='agent',
            field=models.ManyToManyField(default=False, to='supdata.agentes'),
        ),
        migrations.AddField(
            model_name='data',
            name='mtto',
            field=models.ManyToManyField(default=False, to='supdata.revision'),
        ),
    ]
