# Generated by Django 5.2 on 2025-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdata', '0012_remove_data_agent_remove_data_mtto_data_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes',
            name='borrartemporales',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='encriptacionhdd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='epc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='sophos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='tenable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='updates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='agent',
            field=models.ManyToManyField(to='supdata.agentes'),
        ),
        migrations.AlterField(
            model_name='data',
            name='mtto',
            field=models.ManyToManyField(to='supdata.revision'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='aplicacionpasta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limpexterna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limpiezadisipador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limpinterna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limppasta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limpram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limpteclado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='limpventilador',
            field=models.CharField(max_length=100),
        ),
    ]
